# main.yml

- name: Set the current MAC address for eth0.
  set_fact:
    pi_mac_address: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"

- name: Set variables based on eth0 MAC address.
  set_fact:
    pi_hostname: "{{ mac_address_mapping[pi_mac_address].name }}"
    pi_ip_address: "{{ mac_address_mapping[pi_mac_address].ip }}"

- name: Set up networking related files.
  template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { template: hostname.j2, dest: /etc/hostname }
    - { template: hosts.j2, dest: /etc/hosts }
    - { template: interfaces.j2, dest: /etc/network/interfaces }
    - { template: resolv.conf.j2, dest: /etc/resolv.conf }
    - { template: dhcpcd.conf.j2, dest: /etc/dhcpcd.conf }
    - { template: wpa_supplicant.conf.j2, dest: /etc/wpa_supplicant/wpa_supplicant.conf }
  notify:
    - update hostname
    - delete dhcp leases

- name: mount QNAP NFS
  action: mount name=/opt/dev src={{ nfs }}:nfs_mount fstype=nfs opts=nolock state=mounted
  sudo: yes

- name: Ensure filesystem is resized
  expand_fs:
  # notify:
  #   - reboot

- name: reboot
  command: shutdown -r now
  async: 0
  poll: 0
  ignore_errors: True
  # notify:
  #   - wait for reboot

- name: wait for reboot
  local_action: wait_for host={{ inventory_hostname }} state=started timeout=30
  sudo: false
